version: "0.1"
globalTimeout: 300
testSuiteTimeout: 120
testSuiteStep: 90
runson: linux
autosplit: true
retryOnFailure: false
maxRetries: 1
concurrency: 2
pre:
  - npm install
  - npx playwright install --with-deps
cacheKey: '{{ checksum "package-lock.json" }}'
cacheDirectories:
  - node_modules
testDiscovery:
  type: raw
  mode: dynamic
  command: grep -nri 'describe' e2e  | sed 's/:test.*//'
testRunnerCommand: npx playwright test $test

jobLabel: [playwright-VanillaJS, linux, autosplit] 

# Enable Reports
report: enabled